'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CCP.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version 26
        '''	1.	Bug fix
        '''		1.1		In product magrins show material when material is dobule clicked also labour.
        '''		1.2		Make the overhead allocation field editable when creating a new company
        '''		1.3		When creating a quote from costing the customer and the quantity will now pull through
        '''	2.	Create production order facility.
        '''	3.	Create job card facility.
        '''	
        '''
        '''Version 25
        '''	1.	Solve the change database problem
        '''	2.	Handle issues regarding 0 VAT charges
        '''	3.	Create ability to copy a product to a new product in  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _New() As String
            Get
                Return ResourceManager.GetString("_New", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCPBigLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCPBigLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gears1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gears1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property large_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("large_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ManyCans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ManyCans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mini_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mini_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mouse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mouse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property people() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("people", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USE [CCP]
        '''GO
        '''
        '''/****** Object:  View [dbo].[lstReceiptDeposit]    Script Date: 23/03/2017 9:50:01 AM ******/
        '''SET ANSI_NULLS ON
        '''GO
        '''
        '''SET QUOTED_IDENTIFIER ON
        '''GO
        '''
        '''CREATE VIEW [dbo].[lstReceiptDeposit]
        '''AS
        '''SELECT        FK_tblQuotHeader, fk_tblInvoiceHeader, txtReceiptType, MAX(dteReceiptDate) AS ReceiptDate, SUM(dblAmount) AS ReceiptAmount
        '''FROM            dbo.tblReceipts
        '''WHERE        (txtReceiptType = N&apos;Deposit&apos;)
        '''GROUP BY FK_tblQuotHeader, fk_tblInvoiceHeader, txtReceiptType
        '''
        '''GO
        '''
        '''USE [CCP]
        '''GO [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SqlScript_1() As String
            Get
                Return ResourceManager.GetString("SqlScript_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property templateMaterial() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("templateMaterial", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property TemplateProduct() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("TemplateProduct", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property templateStaff() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("templateStaff", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
